sudo: required
services:
  - docker

before install:
  - docker build -t mowen98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mowen98/react-test npm test

after_success:
  - docker build -t mowen98/multi-client ./client
  - docker build -t mowen98/multi-nginx ./nginx
  - docker build -t mowen98/multi-server ./server
  - docker build -t mowen98/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mowen98/multi-client
  - docker push mowen98/multi-nginx
  - docker push mowen98/multi-server
  - docker push mowen98/multi-worker